CREATE TABLE [dbo].[x12_841_code_list] (
    [x12_841_code_list_id]               INT              IDENTITY (1, 1) NOT NULL,
    [x12_transaction_id]                 INT              NULL,
    [x12_codeset_id]                     INT              NULL,
    [L1000_spi01_security_level_code]    CHAR (2)         NULL,
    [L1000_spi04_entity_title]           VARCHAR (132)    NULL,
    [L1000_spi05_entity_purpose]         VARCHAR (80)     NULL,
    [L1000_rdt04_171_revision_date]      CHAR (8)         NULL,
    [L1000_rdt04_007_revision_date]      CHAR (8)         NULL,
    [L1100_n101_entity_id_code]          CHAR (3)         NULL,
    [L1100_n102_source_nm]               VARCHAR (60)     NULL,
    [L2000_hl01_hierarchical_id_num]     VARCHAR (12)     NULL,
    [L2000_hl03_hierarchical_child_code] CHAR (1)         NULL,
    [L2100_spi01_security_level_code]    CHAR (2)         NULL,
    [L2100_spi02_ref_id_qual]            CHAR (3)         NULL,
    [L2100_spi03_code_value]             VARCHAR (30)     NULL,
    [L2100_spi04_entity_title]           VARCHAR (132)    NULL,
    [L2100_msg01_message_text1]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text2]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text3]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text4]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text5]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text6]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text7]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text8]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text9]          VARCHAR (264)    NULL,
    [L2100_msg01_message_text10]         VARCHAR (264)    NULL,
    [error]                              BIT              NOT NULL,
    [processed]                          BIT              NOT NULL,
    [active]                             BIT              NOT NULL,
    [modified_by]                        UNIQUEIDENTIFIER NOT NULL,
    [modified_date]                      DATETIME         NOT NULL,
    [created_by]                         UNIQUEIDENTIFIER NOT NULL,
    [created_date]                       DATETIME         NOT NULL,
    [timestamp]                          ROWVERSION       NOT NULL,
    CONSTRAINT [PK_x12_841_code_list] PRIMARY KEY CLUSTERED ([x12_841_code_list_id] ASC)
);

